### ISSUE TITLE
When using Noxy's Multidirectional Trains mod, LTN Dispatcher forgets old train state when locomotive is "rotated"

### ISSUE THREAD

**Issue by kirazy** [Yousei9/Logistic-Train-Network#109]
Symptom: LTN dispatcher generates duplicate requests to the max number of trains for a given station (i.e. if a request for 75k crude is needed, and the station can handle up to 4 trains, it will generate 4 trains for the same request).

My hypothesis: When the rear train is rotated, Factorio is "remaking" the train, so it's not technically the same train, and so LTN regenerates the request as it doesn't think any train is assigned.

Latest version of Factorio, LTN, and Noxy's Multidirectional Trains (0.16.30, 1.7.5, 0.0.1 respectively.)

Addendum: I posted this first on their end, and felt they provided an informative reply so figured I'd repost here, with a link to the issue there:

https://github.com/CyaNox/Noxys_Multidirectional_Trains/issues/2

**Comment by Yousei9** [comment]
LTN invalidates active deliveries whenever train.id changes.
This prevents deliveries being active when the corresponding train has been destroyed or removed by script.
I see no reason to change this.

**Comment by Yousei9** [comment]
I looked over this issue again.

Migrating ids whenever on_train_created is fired can have undefined effects.
When coupling two trains Factorio seems to take the schedule of the lower id for the resulting train. Together with the unfixed https://github.com/CyaNox/Noxys_Multidirectional_Trains/issues/7 chances of messing up LTN networks are quite high.

I prefer failing into a defined state rather than something failing into a semi random state.
