### ISSUE TITLE
Change license to less permissive version

### ISSUE THREAD

**Issue by realvictorprm** [Yousei9/Logistic-Train-Network#123]
Hello @Yousei9,

your currently license wouldn't allow to redistribute your mod with slight modifications (e.g. if someone would want a feature you dislike and would like to use most of your code etc.). 

Would it be possible to change the license in such a way that redistribution of your mod with modifications is allowed without explicit permission?

Cheers,
~ Victor

**Comment by realvictorprm** [comment]
Besides that I would suggest to use a more common open source license like Apache or MIT because in case of any issues courts would already know how to handle such cases. Just my two cents here 😃

**Comment by Yousei9** [comment]
No, LTNs license will never allow rebranding or redistribution modified or not.
That restriction is not available on any open source license, which is why I use such restrictive custom licenses.

If you want something changed bring good examples of why it should be changed and how it would benefit everyone and not just your specific case and i will adopt those changes into the official release.
