### ISSUE TITLE
LTN crashes when starting second game with New Game+

### ISSUE THREAD

**Issue by dewiniaid** [Yousei9/Logistic-Train-Network#139]
I get the following error with LTN when using the New Game+ mod and starting a 'new' game with said mod:

```
Error while running event LogisticTrainNetwork::on_train_created (ID 66)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	__LogisticTrainNetwork__/control.lua:1752: in function 'setLamp'
	__LogisticTrainNetwork__/control.lua:434: in function 'TrainLeaves'
	__LogisticTrainNetwork__/control.lua:515: in function <__LogisticTrainNetwork__/control.lua:509>
```

I suspect this is due to New Game+ effectively destroying the surface while LTN is working with it, and a check for entity.is_valid() in the correct place would probably fix it

**Comment by Yousei9** [comment]
This stems from NewGame+ removing LTN's script managed IO entities without calling the proper remove handlers.

It's up to the author of NewGame+ to ensure his scripts remove existing entities without crashing other mods. For LTN the proper way to remove a stop is to only remove the stop and let LTN's scripts remove the other 3 entities.

I'm not going to reduce performance through redundant failsafes running multiple times per tick just to accommodate for other mods sloppy programming.

**Comment by dewiniaid** [comment]
Looking at the [relevant code in NewGame+[(https://github.com/Bilka2/NewGamePlus/blob/master/control.lua#L475), it looks like it does not remove entities so much as it deletes entire map chunks (or surfaces, if not Nauvis).  Sadly, there's no event for `on_chunk_destroyed`.

However, `on_pre_surface_deleted` and `on_surface_deleted` are things that LTN could potentially catch and use to clean up if some other mod (not necessarily NewGame+) should delete surfaces that happen to contain LTN train stops.

I'm going to post this on the [NewGame+ Github](https://github.com/Bilka2/NewGamePlus) as well.

**Comment by Bilka2** [comment]
I can't notify you when your entities are deleted. Doing that would lead my mod taking up gigabytes of RAM due to the creation of so many LuaEntity objects to raise the events on.

I can only offer you to raise an event when I delete chunks, but that will still mean that many other mods that delete chunks or destroy entities can crash your mod. I am not comfortable with raising pre surface deleted, so how would you feel about me raising a event called `on_pre_chunk_deleted`? I can add that to my mod, but you will still have to set up your mod to listen for it.

Anyways, I'd recommend you to check .valid or you will always run into these problems. There is no reason not to check that.

**Comment by Yousei9** [comment]
Removing surfaces and chunks without implicitly raising destroyed events for affected entities seems like a terrible design choice.
It's always better to do additional work in such rare occasions when chunks or whole surfaces are removed than to have every mod constantly do validation checks that return true 99% of the time anyway.

I remember having almost the exact same discussion with Mooncat when Creative Mode crashed LTN for the same reason. Since then Creative Mode allows blacklisting entities through remote call.

Are you deleting the whole surface or just chunks?
It would be simpler to remove all LTN stops on a given surface in on_pre_surface_deleted than by chunk since I already have that necessary information in table.

**Comment by Yousei9** [comment]
I didn't think it'd bloat memory that much.

Currently there is no on_pre_chunk_deleted event. So listening to that to properly remove entities being placed across 2 or even 4 chunks isn't going to happen anyway.

A custom event containing surface id, in case nauvis id changes or you change your code and fire it for every surface instead of on_pre_surface_deleted, would be ideal for me to handle this.
Just let me know what the event name is and if i have to treat it any different from built in events.

**Comment by Bilka2** [comment]
Okay, I have added the event, it gives you a surface_index, like pre_surface_deleted. Subscribing to mod events work differently than normal events, I have left a small guide in my code: https://github.com/Bilka2/NewGamePlus/blob/master/control.lua#L12-L31

**Comment by Yousei9** [comment]
Can I also register the function i just wrote for on_pre_surface_deleted like this too?
`script.on_event(remote.call("newgameplus", "get_on_pre_surface_cleared_event"),  OnSurfaceRemoved)`

**Comment by Bilka2** [comment]
Yes, that also works.

**Comment by Yousei9** [comment]
Thanks it should work now. Can you give it a try I have no multi surface test save ready.

**Comment by Bilka2** [comment]
It works.
