### ISSUE TITLE
Fool proof tank wagons

### ISSUE THREAD

**Issue by StephanSteinert** [Yousei9/Logistic-Train-Network#185]
Hey,

if you decide this issue is not your problem at all i accept it but first please read it.

I suggest to add an option for revalidating emptyish tank wagons on requester station leave.

This means, if a train leaves a LTN requester station with a tank wagon and the wagon says it's empty just flush it's fluidbox as failsafe to remove some possible 0.1 residues.

Cu, steinio

**Comment by Yousei9** [comment]
It would be quite simple to add this to LTN, or any general train mod. However I don't feel like removing all small hurdles benefits gameplay.

I'm no fan of automatically purging fluids or items for any reason. This can go wrong quickly, leading to expensive products being lost.
Coming up with safe station designs and depots as secondary safety net is a lot more engaging than toggling an option cleaning fluids automatically.

**Comment by NetTecture** [comment]
This was nice before they started not allowing fluid mixing - you could just dump fluid into something that gets rid of it. Now, it is pretty much impossible to quarantee that a fluid pump empties it.

As alternative: What about adding a condition that gets added: Trains ONLY leave depot when they are empty (no cargo, no fluid) - this takes care of non-mixing because whatever mechanism you ahve to get rid of fluids, has time to empty the pipes and reset.

**Comment by perkinslr** [comment]
You *can* implement that with the circuit network easily enough.  Read the train contents from the station; only send the "is depot" signal to the input if the train is empty.

**Comment by RalfJung** [comment]
> You can implement that with the circuit network easily enough. Read the train contents from the station; only send the "is depot" signal to the input if the train is empty.

Unfortunately, the game considers a train "empty" if all fluids are <1. I had lots of trouble with a multi-fluid requester station because trains would stop being unloaded when <1 fluid was left in them.

I wish there was a way to get a circuit-network information for what the delivery of the current train is. For provider stations, that grey combination in the LTN station outputs what the train is requesting; it would be great if requester stations could likewise output that the train is *bringing*. Then the pumps could be conditioned on that, and there would be no problem with trains that have <1 fluid left.

**Comment by Yousei9** [comment]
Fluids don't mix. As long as an input is found by a fluid network it will lock the entire network to that fluid, pumps extracting from wagons included.
Fluid unloading stations can be built dumb with no circuit control on pumps whatsoever.

**Comment by RalfJung** [comment]
> Fluid unloading stations can be built dumb with no circuit control on pumps whatsoever.

If that's possible, I have not figured out how. Here's what happens when I build a dumb station:
say we have a pump P connected to a tank T that contains petroleum. Now a light oil train arrives. The pump connects to the train and sucks in light oil. Fluids do not mix, so the light oil cannot leave the pump into the tank. Now we have T with petroleum and P with light oil. Now a petroleum train arrives, but P is unable to take out the petroleum because it is full of light oil!

So when I built a dump multi-fluid train station based on "fluids don't mix", it got stuck very quickly.

**Comment by RalfJung** [comment]
However, I have recently learned that requester train stops *do* output something on this little grey/brown constant combinator: for every liquid the train is supposed to bring, they output -1. So we can use that to control the pumps of the station, and entirely ignore the train contents.

**Comment by Yousei9** [comment]
Disregard my previous comment, you are right, pumps don't lock themselves to the fluidbox behind them.
