### ISSUE TITLE
Add signal to disable Notifications

### ISSUE THREAD

**Issue by sebbi08** [Yousei9/Logistic-Train-Network#261]
Hi,

i would like to enable notifications for new build stations but also want to disable them once i got the station running.

This would work for error messages with the Disable Warning signals.

So one idea was to have a signal that is disabling Notifications for certain stations.

**Comment by credomane** [comment]
Sounds like this belongs as part of this feature request since it is along the same lines.

I'd love to see the "Message Level" be made a per-player settings as well as the default value being made "Errors & Warnings". Getting chat spammed because I forgot to turn that off every single map starts to wear on you after a while to say the least.

**Comment by Yousei9** [comment]
Not possible with the way chat works.

Map settings set from main menu are applied to new games and games without settings in save data.
