### ISSUE TITLE
Issue with the LTN output combinator when serving multi-item requests

### ISSUE THREAD

**Issue by elendilo** [Yousei9/Logistic-Train-Network#272]
I'm playing Angel's with LTN and a few QoL mods and running into following issue (sorry I didn't read through all issues here to find a match):

I'm trying to use multiple input/output warehouses with stations [a.k.a. multi-stations] (i.e. they provide or request multiple types of items). To go around the eventual mutli item request i use regular filter inserters that have multiple filter slots. So far so good. But sometimes, the train schedule shows only one type of item, but the output combinator on the LTN station shows that type plus a couple of some other type (e.g. crushed stone). That then throws a wrench into everything, as the train gets filled with mixed goods, or gets stuck if the type of item in the schedule somehow doesn't get filled properly and is full of stone instead.

Can supply screenshots/logs/etc.

**Comment by elendilo** [comment]
screenshots:
![ltn_error_out_signal](https://user-images.githubusercontent.com/34356118/134241764-99b20688-2a36-4138-83ec-0151daad1114.png)
![ltn_error_train_sched](https://user-images.githubusercontent.com/34356118/134241813-e8727512-115a-4e92-81be-4c72dd5dc650.png)

**Comment by Yousei9** [comment]
Check if it's this issue: https://forums.factorio.com/viewtopic.php?f=214&t=90090

**Comment by mrvn** [comment]
That looks to me like the train arrived with 2 crushed stone left over in the cargo wagon. In those cases the LTN output shows both the existing cargo and the requested items. Check all your depots if there are any trains with items left in them. If so I would say that is the problem and not an LTN bug.

A likely cause is this: You don't stop the inserters from loading items before the train leaves.

Say a train comes requesting crushed stone. The inserters pick it up and load the train full. At the end when the cargo wagon is full some inserters will be left with crushed stone in their hand. Then the next train comes in requesting crushed ore (less than a wagon full or it would already block there). First it gets the left over crushed stone, then the crushed ore. If your unloading station uses filter inserters too it will only unload crushed ore leaving the crushed stone in the wagon. And then when the train goes to the station again the LTN output will show 2 crushed stone as well as the requested items.

If you don't load count perfect you have to set reserved slots for the station so it never requests a completely full train. Setting the option to finish loading is also a good idea. You must also program the filter inserters using "<LTN output> - <train content>" so if a request for say 1000 crushed ore comes in they do stop once 1000 crushed ore are loaded. Otherwise the reserved slot won't help as you always load the wagon full.

Note: Have you considered what to do when LTN actually does send a train requesting crushed stone and crushed ore? If someone requests both LTN can merge them into one delivery.

**Comment by Yousei9** [comment]
Should be mitigated by 1.16.8.
Full fix is only possible by making station designs that don't lock up inserters.
